In [1]:
import pandas as pd

In [2]:
melbourne_file_path = 'melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path)

FileNotFoundError: [Errno 2] File b'melb_data.csv' does not exist: b'melb_data.csv'

In [3]:
melbourne_file_path = '../melb_data.csv'
# read the data and store data in DataFrame titled melbourne_data
melbourne_data = pd.read_csv(melbourne_file_path)

In [4]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [5]:
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [6]:
melbourne_data = melbourne_data.dropna(axis=0)

In [7]:
melbourne_data.Price

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
           ...
12205     601000.0
12206    1050000.0
12207     385000.0
12209     560000.0
12212    2450000.0
Name: Price, Length: 6196, dtype: float64

In [8]:
melbourne_data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.00,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.00,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
9,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,2.0,220.0,75.00,1900.0,Yarra,-37.80100,144.99890,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.00,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
12,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12/11/2016,2.5,3067.0,...,2.0,1.0,0.0,94.00,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
15,Abbotsford,16 William St,2,h,1310000.0,S,Jellis,15/10/2016,2.5,3067.0,...,1.0,2.0,238.0,97.00,1890.0,Yarra,-37.80900,144.99760,Northern Metropolitan,4019.0
16,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16/07/2016,2.5,3067.0,...,2.0,1.0,113.0,110.00,1880.0,Yarra,-37.80560,144.99300,Northern Metropolitan,4019.0
17,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16/07/2016,2.5,3067.0,...,1.0,1.0,138.0,105.00,1890.0,Yarra,-37.80210,144.99650,Northern Metropolitan,4019.0
19,Abbotsford,42 Valiant St,2,h,890000.0,S,Biggin,17/09/2016,2.5,3067.0,...,1.0,1.0,150.0,73.00,1985.0,Yarra,-37.80110,145.00040,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.00,1900.0,Yarra,-37.80730,144.99520,Northern Metropolitan,4019.0
23,Abbotsford,6/219 Nicholson St,2,u,500000.0,S,Collins,18/06/2016,2.5,3067.0,...,1.0,1.0,0.0,60.00,1970.0,Yarra,-37.80150,144.99720,Northern Metropolitan,4019.0
24,Abbotsford,52a William St,2,h,1100000.0,PI,Biggin,18/06/2016,2.5,3067.0,...,2.0,1.0,124.0,135.00,2013.0,Yarra,-37.80790,144.99770,Northern Metropolitan,4019.0
25,Abbotsford,49 Park St,2,h,1315000.0,S,Marshall,19/11/2016,2.5,3067.0,...,1.0,0.0,147.0,85.00,1900.0,Yarra,-37.80800,144.99400,Northern Metropolitan,4019.0
27,Abbotsford,48 Abbotsford St,3,h,1447500.0,PI,Nelson,22/08/2016,2.5,3067.0,...,3.0,1.0,166.0,174.00,2012.0,Yarra,-37.80170,145.00010,Northern Metropolitan,4019.0
29,Abbotsford,159 Park St,2,h,1135000.0,S,Nelson,22/08/2016,2.5,3067.0,...,2.0,2.0,98.0,128.00,1920.0,Yarra,-37.80050,144.99520,Northern Metropolitan,4019.0
32,Abbotsford,60 Stafford St,3,h,1290000.0,S,Biggin,25/02/2017,2.5,3067.0,...,1.0,1.0,168.0,124.00,1950.0,Yarra,-37.80070,144.99580,Northern Metropolitan,4019.0
33,Abbotsford,11/205 Gipps St,1,u,470000.0,S,Nelson,26/07/2016,2.5,3067.0,...,1.0,1.0,0.0,50.00,2013.0,Yarra,-37.80550,144.99610,Northern Metropolitan,4019.0
34,Abbotsford,47 Studley St,2,h,1180000.0,S,Jellis,27/11/2016,2.5,3067.0,...,1.0,0.0,162.0,91.00,1900.0,Yarra,-37.80160,144.99560,Northern Metropolitan,4019.0
35,Abbotsford,45 Yarra St,3,h,1195000.0,SP,Jellis,27/11/2016,2.5,3067.0,...,2.0,1.0,120.0,128.00,1998.0,Yarra,-37.80220,144.99540,Northern Metropolitan,4019.0
36,Abbotsford,200 Nicholson St,2,h,1012500.0,S,Nelson,28/05/2016,2.5,3067.0,...,1.0,0.0,182.0,82.00,1900.0,Yarra,-37.80210,144.99760,Northern Metropolitan,4019.0
37,Abbotsford,27 Charles St,2,h,1030000.0,S,Biggin,30/07/2016,2.5,3067.0,...,1.0,1.0,172.0,81.00,1930.0,Yarra,-37.80860,144.99460,Northern Metropolitan,4019.0
38,Airport West,154 Halsey Rd,3,t,840000.0,PI,Nelson,3/09/2016,13.5,3042.0,...,2.0,1.0,303.0,225.00,2016.0,Moonee Valley,-37.71800,144.87800,Western Metropolitan,3464.0
39,Airport West,50 Bedford St,3,h,730000.0,VB,Nelson,3/12/2016,13.5,3042.0,...,2.0,1.0,0.0,145.00,1965.0,Moonee Valley,-37.72030,144.87550,Western Metropolitan,3464.0
40,Airport West,50 Bedford St,3,h,770000.0,SP,Nelson,4/03/2017,13.5,3042.0,...,2.0,1.0,0.0,145.00,1965.0,Moonee Valley,-37.72030,144.87550,Western Metropolitan,3464.0
41,Airport West,23 Hart St,2,h,603000.0,S,Nelson,4/03/2017,13.5,3042.0,...,1.0,1.0,272.0,84.00,1950.0,Moonee Valley,-37.72940,144.88800,Western Metropolitan,3464.0
42,Airport West,1/80 Hawker St,3,t,700000.0,S,Brad,4/03/2017,13.5,3042.0,...,2.0,2.0,239.0,134.00,2009.0,Moonee Valley,-37.72180,144.88370,Western Metropolitan,3464.0
43,Airport West,1/37 Hillside Gr,3,h,600000.0,S,Maddison,4/03/2017,13.5,3042.0,...,1.0,1.0,290.0,116.00,1980.0,Moonee Valley,-37.72730,144.87440,Western Metropolitan,3464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12154,Seaford,13 Hayman Av,4,h,880000.0,S,O'Brien,29/07/2017,35.4,3198.0,...,2.0,2.0,535.0,199.00,1970.0,Frankston,-38.09683,145.12981,South-Eastern Metropolitan,8077.0
12156,Seddon,2/70 Windsor St,2,h,945000.0,SP,Village,29/07/2017,5.1,3011.0,...,1.0,1.0,126.0,65.00,1890.0,Maribyrnong,-37.80473,144.89095,Western Metropolitan,2417.0
12157,South Kingsville,89A New St,3,t,730000.0,S,Sweeney,29/07/2017,6.2,3015.0,...,2.0,2.0,340.0,135.00,2000.0,Hobsons Bay,-37.83172,144.86683,Western Metropolitan,984.0
12159,South Melbourne,372 Coventry St,2,h,980000.0,VB,Marshall,29/07/2017,1.9,3205.0,...,1.0,0.0,64.0,112.00,2000.0,Port Phillip,-37.83326,144.95464,Southern Metropolitan,5943.0
12164,South Yarra,9/17 Howitt St,2,u,570000.0,VB,Ray,29/07/2017,2.7,3141.0,...,1.0,1.0,0.0,64.00,1965.0,Stonnington,-37.84679,145.00206,Southern Metropolitan,14887.0
12168,St Kilda,45/151 Fitzroy St,2,u,600000.0,VB,hockingstuart,29/07/2017,5.0,3182.0,...,1.0,1.0,0.0,82.00,1930.0,Port Phillip,-37.85911,144.97900,Southern Metropolitan,13240.0
12169,Sunbury,1/6 Anthony St,2,u,360000.0,SP,Brad,29/07/2017,31.7,3429.0,...,1.0,1.0,143.0,112.00,1999.0,Hume,-37.57063,144.70693,Western Metropolitan,14092.0
12171,Sunbury,19 Muirfield Dr,3,h,475000.0,S,Leeburn,29/07/2017,31.7,3429.0,...,1.0,4.0,754.0,131.00,1985.0,Hume,-37.58442,144.75565,Western Metropolitan,14092.0
12172,Sunbury,26 Xavier Ct,3,h,495000.0,S,One,29/07/2017,31.7,3429.0,...,2.0,2.0,563.0,150.00,1994.0,Hume,-37.57499,144.75329,Western Metropolitan,14092.0
12173,Sunshine West,2 Day St,3,h,695000.0,S,Barry,29/07/2017,10.5,3020.0,...,1.0,0.0,694.0,113.60,1950.0,Brimbank,-37.78871,144.81369,Western Metropolitan,6763.0
12174,Sunshine West,73 Hilma St,3,h,760000.0,S,Barry,29/07/2017,10.5,3020.0,...,1.0,2.0,1143.0,100.00,1980.0,Brimbank,-37.79135,144.79948,Western Metropolitan,6763.0
12175,Sunshine West,18 Marchant Cr,3,h,583500.0,S,S&L,29/07/2017,10.5,3020.0,...,1.0,1.0,672.0,110.00,1970.0,Brimbank,-37.80118,144.80996,Western Metropolitan,6763.0
12177,Sydenham,23 Contursi Dr,3,h,585000.0,S,Prof.,29/07/2017,18.0,3037.0,...,2.0,2.0,662.0,232.00,2004.0,Brimbank,-37.70525,144.75699,Western Metropolitan,3640.0
12180,Templestowe Lower,51 Jeffrey St,3,h,1245000.0,S,Barry,29/07/2017,12.4,3107.0,...,2.0,2.0,779.0,135.00,1970.0,Manningham,-37.76311,145.10494,Eastern Metropolitan,5420.0
12181,Templestowe Lower,13 Melaleuca Av,6,h,2000000.0,VB,Barry,29/07/2017,12.4,3107.0,...,3.0,2.0,1054.0,235.00,1970.0,Manningham,-37.77404,145.11703,Eastern Metropolitan,5420.0
12183,Thomastown,2/1 Charles St,2,u,407000.0,S,HAR,29/07/2017,15.3,3074.0,...,1.0,1.0,140.0,78.00,2010.0,Whittlesea,-37.68199,145.01744,Northern Metropolitan,7955.0
12186,Thornbury,13 Rayment St,3,h,891000.0,S,Nelson,29/07/2017,7.0,3071.0,...,2.0,2.0,199.0,140.00,1999.0,Darebin,-37.75948,144.99615,Northern Metropolitan,8870.0
12187,Tullamarine,1/171 Melrose Dr,3,h,615500.0,S,hockingstuart,29/07/2017,12.9,3043.0,...,2.0,1.0,238.0,118.00,2011.0,Hume,-37.70322,144.88236,Western Metropolitan,3296.0
12188,Tullamarine,9/200 Melrose Dr,2,u,300000.0,SP,Jason,29/07/2017,12.9,3043.0,...,1.0,1.0,0.0,66.32,1980.0,Hume,-37.69815,144.88019,Western Metropolitan,3296.0
12192,Wantirna South,11 Kirrum Cl,5,h,1310000.0,S,Harcourts,29/07/2017,14.7,3152.0,...,3.0,2.0,818.0,255.00,1985.0,Knox,-37.87846,145.24212,Eastern Metropolitan,7082.0
12197,Werribee,18 Conquest Dr,4,h,645000.0,PI,hockingstuart,29/07/2017,14.7,3030.0,...,2.0,2.0,555.0,237.00,2002.0,Wyndham,-37.89359,144.66911,Western Metropolitan,16166.0
12198,Werribee,46 Coventry Dr,4,h,482500.0,S,YPA,29/07/2017,14.7,3030.0,...,2.0,0.0,533.0,170.00,1980.0,Wyndham,-37.89337,144.64003,Western Metropolitan,16166.0
12199,Werribee,13b Kingfisher Ct,3,u,394000.0,PI,hockingstuart,29/07/2017,14.7,3030.0,...,2.0,4.0,287.0,137.00,2013.0,Wyndham,-37.87895,144.67070,Western Metropolitan,16166.0
12202,Westmeadows,43 Bamford Av,4,h,821000.0,S,YPA,29/07/2017,16.5,3049.0,...,3.0,2.0,544.0,264.00,1997.0,Hume,-37.67841,144.87924,Northern Metropolitan,2474.0
12203,Westmeadows,4 Pershore Ct,3,h,635000.0,S,Barry,29/07/2017,16.5,3049.0,...,2.0,1.0,691.0,177.00,1975.0,Hume,-37.68026,144.88468,Northern Metropolitan,2474.0
12205,Whittlesea,30 Sherwin St,3,h,601000.0,S,Ray,29/07/2017,35.5,3757.0,...,2.0,1.0,972.0,149.00,1996.0,Whittlesea,-37.51232,145.13282,Northern Victoria,2170.0
12206,Williamstown,75 Cecil St,3,h,1050000.0,VB,Williams,29/07/2017,6.8,3016.0,...,1.0,0.0,179.0,115.00,1890.0,Hobsons Bay,-37.86558,144.90474,Western Metropolitan,6380.0
12207,Williamstown,2/29 Dover Rd,1,u,385000.0,SP,Williams,29/07/2017,6.8,3016.0,...,1.0,1.0,0.0,35.64,1967.0,Hobsons Bay,-37.85588,144.89936,Western Metropolitan,6380.0
12209,Windsor,201/152 Peel St,2,u,560000.0,PI,hockingstuart,29/07/2017,4.6,3181.0,...,1.0,1.0,0.0,61.60,2012.0,Stonnington,-37.85581,144.99025,Southern Metropolitan,4380.0
12212,Yarraville,54 Pentland Pde,6,h,2450000.0,VB,Village,29/07/2017,6.3,3013.0,...,3.0,2.0,1087.0,388.50,1920.0,Maribyrnong,-37.81038,144.89389,Western Metropolitan,6543.0

In [9]:
y = melbourne_data.Price

In [10]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [11]:
X = melbourne_data[melbourne_features]

In [12]:
X.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

In [13]:
X.head()

   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

In [14]:
X.tail()

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
12205      3       2.0     972.0  -37.51232   145.13282
12206      3       1.0     179.0  -37.86558   144.90474
12207      1       1.0       0.0  -37.85588   144.89936
12209      2       1.0       0.0  -37.85581   144.99025
12212      6       3.0    1087.0  -37.81038   144.89389

In [15]:
from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit model
melbourne_model.fit(X, y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=1, splitter='best')

In [16]:
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]

In [17]:
print(melbourne_model.predict(X.tail()))

[ 601000. 1050000.  385000.  560000. 2450000.]

In [18]:
print(melbourne_model.predict(y.tail()))

ValueError: Expected 2D array, got 1D array instead:
array=[ 601000. 1050000.  385000.  560000. 2450000.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [19]:
print(melbourne_model.predict(X.tail()))

[ 601000. 1050000.  385000.  560000. 2450000.]

In [20]:
print(melbourne_model.predict(X.head()))

[1035000. 1465000. 1600000. 1876000. 1636000.]

In [21]:
print(melbourne_model.predict(X)

SyntaxError: unexpected EOF while parsing (<ipython-input-21-d9415132c4dd>, line 1)

In [22]:
print(melbourne_model.predict(X.tail()[1]))

KeyError: 1